# Generated by Django 5.1.5 on 2025-01-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_followers_delete_statistics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('follower', 'following')},
        ),
    ]
