# Generated by Django 5.1.2 on 2025-01-24 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarked_posts', through='users.Bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
